apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-clone
  template:
    metadata:
      labels:
        app: reddit-clone
    spec:
      containers:
        - name: reddit-clone
          image: shubham4477/reddit-clone:v1
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_FIREBASE_API_KEY
              value: "AIzaSyBqe95nCUomWkU9PnZT_OlV_NCAZnTmyz0"
            - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
              value: "reddit-clone-r.firebaseapp.com"
            - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
              value: "reddit-clone-r"
            - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
              value: "reddit-clone-r.appspot.com"
            - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
              value: "233455437474"
            - name: NEXT_PUBLIC_FIREBASE_APP_ID
              value: "1:233455437474:web:5f21ac4b94a42fddb379fb"
            - name: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
              value: "G-3L9HMZR4XQ"
